var _location="商品",review_tr='<div class="rows foxe3"></div>',review_td='<div class="row">    <div class="timestamp"><timestamp></div>    <div class="buyer"><b><buyer></b> 寫了：</div>    <div class="comment"><div>『</div><div><comment></div><div>』</div></div>    <div class="image flex pointer"><img src="<image>" /></div></div>',item_info_a='<a href="/search?<k>=<v>"><text></a>';
window.item_js=function(e){delete window.item_js;var h=window.location.href.split("/item/").slice(-1)[0],d={item_sku:null,quantity_changed:!0,sku_active:null,quantity_active:null,app:e};d=$.extend({},d,window.common_js());$.get("/common.html",function(b){d.append_stock(b,"div#for_item");$("div#quantity_plus").click(d.quantity_plus_e(d));$("div#quantity_minus").click(d.quantity_minus_e(d));$("div#add_to_cart_descriptor").click(function(){if(!d.sku_active||0===d.quantity_active)return alert(e.dialog_resource.alert_sku_select);
var a="&sku="+d.sku_active;a=a.repeat(d.quantity_active);e.api_post("request=cart&op=add"+a,function(f,p){success(e.dialog_resource.success_sku_select)})});$("div#select_sku").click(function(){d.setup_sku_select(d,h,function(){return 1},void 0,function(){$("div#stock div#skus select").trigger("change")})});e.api_post("request=views&mfcid="+h,void 0,void 0,!1)});e.api_post("request=item_info&mfcid="+h,function(b,a){function f(c){$("div#loading").finish().fadeIn();e.image_preview_e(c,!1);var k=setInterval(function(){$("div#preview img")[0].complete&&
(clearInterval(k),$("div#loading").finish().fadeOut())},100),v=!!c.target;c=c.target||c;m=q.index(c);$("div#preview div.description").html(m+1+" / "+q.length);v?$("div#preview").fadeIn():$("div#preview").show();$("div#preview div.preview_next, div#preview div.preview_prev").css({display:"flex"})}function p(c){return function(k){k.preventDefault();k.stopPropagation();0<c&&m+1<=q.length-1?f(q[m+1]):0>c&&0<=m-1&&f(q[m-1])}}function r(){n[0].scrollTo(0,0);setTimeout(function(){var c=n.children().outerWidth(),
k=n.width();c>k?n.animate({scrollLeft:c-k},9*c,"linear",function(){setTimeout(r,1E3)}):setTimeout(r,1E3)},1E3)}console.log(a);for(b=0;b<a.length;b++)if(6===b)for(var g=0;g<a[6].length;g++)0===a[6][g].indexOf("|mfc|")&&(a[6][g]=a[6][g].replace("|mfc|","https://static.myfigurecollection.net/upload/pictures/"));else{var u=$("div#item div#item_info div[i='"+b+"'] span");if(0!==u.length){var l=a[b];if(Array.isArray(l)){var t="";for(g=0;g<l.length;g++)t&&(t+="・"),t+=item_info_a.replace(/<text>/g,l[g][1]).replace(/<k>/g,
u.parent().attr("id")).replace(/<v>/g,l[g][0]);l=t}null!==l&&u.html(l)}}b=e.dialog_resource.img_src_mfcid.replace(/<mfcid>/g,h);0===a[6].length&&(a[6]=[b]);(new Slideshow).setup(a[6],f);var q=$("div.glider-track div.glider-slide"),m=0;$("div#preview div.preview_next").click(p(1));$("div#preview div.preview_prev").click(p(-1));1===a[4]&&-1===document.cookie.indexOf("off_blur")&&($("#slideshow img").addClass("blur"),warn("<div>本網頁可能含有令人反感、十六歲以上、成人內容。\n未滿十六歲人士必須在成人陪同下瀏覽。\n本網域嚴禁虛報年齡或違法瀏覽等行為。</div>",{cancel:"離開",
confirm:"同意並進入"},function(c){c?$("#slideshow img").removeClass("blur"):($("#slideshow img").parent().off("mousedown"),window.history.back())}));var n=$("div#item_info div#name span").eq(0);a=n.text().split("・");for(b=0;b<a.length;b++)a[b]="<a href='/search?keyword="+encodeURIComponent(a[b])+"'>"+a[b]+"</a>";n.html(a.join("・"));r()});e.api_post("request=review&op=get&mfcid="+h,function(b,a){if(0!==a.length){$("div#review #no_review").hide();$("div#review span#amount_review").text(a.length);a=a.sort(function(p,
r){return window.str2epoch(r[0])-window.str2epoch(p[0])});b="";for(var f=0;f<a.length;f++)b+=review_td.replace(/<timestamp>/g,a[f][0]).replace(/<buyer>/g,a[f][1]).replace(/<comment>/g,$("<div/>").text(a[f][3]).html()).replace(/<image>/g,a[f][4]?"/upload/review/"+a[f][4]:"");$("div#review div.content").append($(review_tr).append(b));$("div#review div.image").click(e.image_preview_e)}});-1!==document.cookie.search(/username=/)&&e.api_post("request=wishlist&op=is_wished&mfcid="+h,function(b,a){a&&$("div#add2wish").addClass("wished").text($("div#add2wish").data("wished"))},
void 0,!1);$("div#review").appendTo("body");$("div#open_review").click(function(){$("div#review").fadeIn()});$("div#close_popup").click(function(){$("div#review").fadeOut().each(function(){$(this).children("div.content")[0].scrollTop=0})});$("div#add2wish").click(function(){-1!==document.cookie.search(/username=/)&&e.api_post("request=wishlist&op=toggle&mfcid="+h,function(b,a){a?$("div#add2wish").addClass("wished").text($("div#add2wish").data("wished")):$("div#add2wish").removeClass("wished").text($("div#add2wish").data("ori"))})});
$("div#open_more_action").click(function(){$("div#more_action").fadeToggle()});$("div#more_action div#user div[id]").click(function(){$("div#open_more_action").click();var b=$("div#cs_page div#cs_info div."+$(this).attr("id"));dialog(void 0,$(this).text(),b.html())});$("div#more_action div#admin div[id]").click(function(){window.open("http://admin.foxe6.kozow.com/shop?"+$(this).text()+"&mfcid="+h,"_blank")});$(window).keyup(function(b){"`"===b.key&&$("div#more_action div#admin").show()})};
