var _location="商品",review_tr='<div class="rows foxe3"></div>',review_td='<div class="row">    <div class="buyer"><b class="no_translate"><buyer></b></div>    <div class="kind"><i>款式：<kind></i></div>    <div class="comment"><comment></div>    <div class="image flex pointer"><img src="<image>" /></div>    <div class="timestamp"><timestamp></div></div>',item_info_a='<a href="/search?<k>=<v>"><text></a>',item_img="<div class='item flex'><a class='image flex<castoff>' href='/item/<mfcid>'><img src='<src>' /></a></div>";
window.item_js=function(c){delete window.item_js;var k=window.location.pathname.split("/item/").slice(-1)[0],e={item_sku:null,quantity_changed:!0,sku_active:null,quantity_active:null,app:c};e=$.extend({},e,window.common_js());$.get("/common.html",function(a){e.append_stock(a,"div#for_item");$("div#quantity_plus").click(e.quantity_plus_e(e));$("div#quantity_minus").click(e.quantity_minus_e(e));$("div#add_to_cart_descriptor").click(function(){if(!e.sku_active||0===e.quantity_active)return alert(c.dialog_resource.alert_sku_select);
var b="&sku="+e.sku_active;b=b.repeat(e.quantity_active);c.api_post("request=cart&op=add"+b,function(f,p){success(c.dialog_resource.success_sku_select)})});$("div#select_sku").click(function(){e.setup_sku_select(e,k,function(){return 1},void 0,function(){$("div#stock div#skus select").trigger("change")})});c.api_post("request=views&mfcid="+k,void 0,void 0,!1)});c.api_post("request=item_info&mfcid="+k,function(a,b){function f(d){$("div#loading").finish().fadeIn();c.image_preview_e(d,!1);var m=setInterval(function(){$("div#preview img")[0].complete&&
(clearInterval(m),$("div#loading").finish().fadeOut())},100),w=!!d.target;d=d.target||d;n=q.index(d);$("div#preview div.description").html(n+1+" / "+q.length);w?$("div#preview").fadeIn():$("div#preview").show();$("div#preview div.preview_next, div#preview div.preview_prev").css({display:"flex"})}function p(d){return function(m){m.preventDefault();m.stopPropagation();0<d&&n+1<=q.length-1?f(q[n+1]):0>d&&0<=n-1&&f(q[n-1])}}function r(){u[0].scrollTo(0,0);setTimeout(function(){var d=u.children().outerWidth(),
m=u.width();d>m?u.animate({scrollLeft:d-m},9*d,"linear",function(){setTimeout(r,1E3)}):setTimeout(r,1E3)},1E3)}console.log(b);for(a=0;a<b.length;a++){var h=$("div#item div#item_info div[i='"+a+"'] span");if(0!==h.length){var l=b[a];if(Array.isArray(l)){for(var v="",g=0;g<l.length;g++)v&&(v+="・"),v+=item_info_a.replace(/<text>/g,l[g][1]).replace(/<k>/g,h.parent().attr("id")).replace(/<v>/g,l[g][0]);l=v}null!==l&&""!==l&&h.html(l)}}a=c.dialog_resource.img_src_mfcid.replace(/<mfcid>/g,k);for(g=0;g<b[6].length;g++)0===
b[6][g].indexOf("|mfc|")&&(b[6][g]=b[6][g].replace("|mfc|","https://static.myfigurecollection.net/upload/pictures/"));0===b[6].length&&(b[6]=[a]);(new Slideshow).setup(b[6],f);var q=$("div.glider-track div.glider-slide"),n=0;$("div#preview div.preview_next").click(p(1));$("div#preview div.preview_prev").click(p(-1));b[4]&&-1===document.cookie.indexOf("off_blur")&&($("#slideshow img").addClass("blur"),warn("<div>本網頁可能含有令人反感、十六歲以上、成人內容。\n未滿十六歲人士必須在成人陪同下瀏覽。\n本網域嚴禁虛報年齡或違法瀏覽等行為。</div>",{cancel:"離開",confirm:"同意並進入"},
function(d){d?$("#slideshow img").removeClass("blur"):($("#slideshow img").parent().off("mousedown"),window.history.back())}));g=$("div#item_info div#name span").eq(0);h=g.text().split("・");for(a=0;a<h.length;a++)h[a]="<a href='/search?keyword="+encodeURIComponent(h[a])+"'>"+h[a]+"</a>";g.html(h.join("・"));var u=$("div#item_info div#discount").eq(0);r();for(a=0;a<b[11].length;a++)$("div#related_items div.content").append(item_img.replace(/<mfcid>/g,b[11][a][0]).replace(/<castoff>/g,b[11][a][1]?" blur":
"").replace(/<src>/g,c.dialog_resource.img_src_mfcid.replace(/<mfcid>/g,b[11][a][0])));$("div#related_items div.content").trigger("scroll")});c.api_post("request=review&op=get&mfcid="+k,function(a,b){if(0!==b.length){$("div#review #no_review").hide();$("div#review span#amount_review").text(b.length);b=b.sort(function(p,r){return window.str2epoch(r[0])-window.str2epoch(p[0])});a="";for(var f=0;f<b.length;f++)a+=review_td.replace(/<timestamp>/g,b[f][0]).replace(/<buyer>/g,b[f][1]).replace(/<comment>/g,
$("<div/>").text(b[f][3]).html()).replace(/<image>/g,b[f][4]?"/upload/review/"+b[f][4]:"").replace(/<kind>/g,b[f][5]);$("div#review div.content").append($(review_tr).append(a)).trigger("scroll");$("div#review div.image").click(c.image_preview_e)}});-1!==document.cookie.search(/username=/)&&c.api_post("request=wishlist&op=is_wished&mfcid="+k,function(a,b){b&&$("div#add2wish").addClass("wished").text($("div#add2wish").data("wished"))},void 0,!1);$("div#review").appendTo("body");$("div#open_review").click(function(){$("div#review").fadeIn()});
$("div#close_popup").click(function(){$("div#review").fadeOut().each(function(){$(this).children("div.content")[0].scrollTop=0})});$("div#add2wish").click(function(){-1!==document.cookie.search(/username=/)&&c.api_post("request=wishlist&op=toggle&mfcid="+k,function(a,b){b?$("div#add2wish").addClass("wished").text($("div#add2wish").data("wished")):$("div#add2wish").removeClass("wished").text($("div#add2wish").data("ori"))})});$("div#open_more_action").click(function(){$("div#more_action").fadeToggle()});
$("div#more_action div#user div[id]").click(function(){$("div#open_more_action").click();var a=$("div#cs_page div#cs_info div."+$(this).attr("id"));dialog(void 0,$(this).text(),a.html())});$("div#more_action div#admin div[id]").click(function(){window.open("http://admin.foxe6.kozow.com/shop?"+$(this).text()+"&mfcid="+k,"_blank")});$(window).keyup(function(a){"`"===a.key&&$("div#more_action div#admin").show()});var t=$("div#review div.content");c.setup_scroll_hints(t);t.trigger("scroll");t=$("div#related_items div.content");
c.setup_scroll_hints(t);t.trigger("scroll");$("a#toc_toggle").click(function(a){a.stopPropagation();a.preventDefault();a=$(this).data("state")?0:1;$(this).data("state",a);$(this).text($(this).data(a.toString()));$("div#toc").toggle();a=$("div#item")[0].scrollTop;$("div#item")[0].scrollTop=0;$("div#item")[0].scrollTop=a;$("div#item")[0].scrollTop+=7*$("div#menu").height()-$("div#toc_top").outerHeight()})};
