var _location="商品",review_tr='<div class="rows foxe3"></div>',review_td='<div class="row">    <div class="buyer"><b class="no_translate"><buyer></b></div>    <div class="kind"><i>款式：<kind></i></div>    <div class="comment"><comment></div>    <div class="image flex pointer"><img src="<image>" /></div>    <div class="timestamp"><timestamp></div></div>',item_info_a='<a href="/search?<k>=<v>"><text></a>';
window.item_js=function(e){delete window.item_js;var h=window.location.pathname.split("/item/").slice(-1)[0],f={item_sku:null,quantity_changed:!0,sku_active:null,quantity_active:null,app:e};f=$.extend({},f,window.common_js());$.get("/common.html",function(a){f.append_stock(a,"div#for_item");$("div#quantity_plus").click(f.quantity_plus_e(f));$("div#quantity_minus").click(f.quantity_minus_e(f));$("div#add_to_cart_descriptor").click(function(){if(!f.sku_active||0===f.quantity_active)return alert(e.dialog_resource.alert_sku_select);
var b="&sku="+f.sku_active;b=b.repeat(f.quantity_active);e.api_post("request=cart&op=add"+b,function(g,n){success(e.dialog_resource.success_sku_select)})});$("div#select_sku").click(function(){f.setup_sku_select(f,h,function(){return 1},void 0,function(){$("div#stock div#skus select").trigger("change")})});e.api_post("request=views&mfcid="+h,void 0,void 0,!1)});e.api_post("request=item_info&mfcid="+h,function(a,b){function g(d){$("div#loading").finish().fadeIn();e.image_preview_e(d,!1);var l=setInterval(function(){$("div#preview img")[0].complete&&
(clearInterval(l),$("div#loading").finish().fadeOut())},100),w=!!d.target;d=d.target||d;m=p.index(d);$("div#preview div.description").html(m+1+" / "+p.length);w?$("div#preview").fadeIn():$("div#preview").show();$("div#preview div.preview_next, div#preview div.preview_prev").css({display:"flex"})}function n(d){return function(l){l.preventDefault();l.stopPropagation();0<d&&m+1<=p.length-1?g(p[m+1]):0>d&&0<=m-1&&g(p[m-1])}}function q(){r[0].scrollTo(0,0);setTimeout(function(){var d=r.children().outerWidth(),
l=r.width();d>l?r.animate({scrollLeft:d-l},9*d,"linear",function(){setTimeout(q,1E3)}):setTimeout(q,1E3)},1E3)}console.log(b);for(a=0;a<b.length;a++)if(6===a)for(var c=0;c<b[6].length;c++)0===b[6][c].indexOf("|mfc|")&&(b[6][c]=b[6][c].replace("|mfc|","https://static.myfigurecollection.net/upload/pictures/"));else{var u=$("div#item div#item_info div[i='"+a+"'] span");if(0!==u.length){var k=b[a];if(Array.isArray(k)){var t="";for(c=0;c<k.length;c++)t&&(t+="・"),t+=item_info_a.replace(/<text>/g,k[c][1]).replace(/<k>/g,
u.parent().attr("id")).replace(/<v>/g,k[c][0]);k=t}null!==k&&""!==k&&u.html(k)}}a=e.dialog_resource.img_src_mfcid.replace(/<mfcid>/g,h);0===b[6].length&&(b[6]=[a]);(new Slideshow).setup(b[6],g);var p=$("div.glider-track div.glider-slide"),m=0;$("div#preview div.preview_next").click(n(1));$("div#preview div.preview_prev").click(n(-1));b[4]&&-1===document.cookie.indexOf("off_blur")&&($("#slideshow img").addClass("blur"),warn("<div>本網頁可能含有令人反感、十六歲以上、成人內容。\n未滿十六歲人士必須在成人陪同下瀏覽。\n本網域嚴禁虛報年齡或違法瀏覽等行為。</div>",
{cancel:"離開",confirm:"同意並進入"},function(d){d?$("#slideshow img").removeClass("blur"):($("#slideshow img").parent().off("mousedown"),window.history.back())}));b=$("div#item_info div#name span").eq(0);c=b.text().split("・");for(a=0;a<c.length;a++)c[a]="<a href='/search?keyword="+encodeURIComponent(c[a])+"'>"+c[a]+"</a>";b.html(c.join("・"));var r=$("div#item_info div#discount").eq(0);q()});e.api_post("request=review&op=get&mfcid="+h,function(a,b){if(0!==b.length){$("div#review #no_review").hide();$("div#review span#amount_review").text(b.length);
b=b.sort(function(n,q){return window.str2epoch(q[0])-window.str2epoch(n[0])});a="";for(var g=0;g<b.length;g++)a+=review_td.replace(/<timestamp>/g,b[g][0]).replace(/<buyer>/g,b[g][1]).replace(/<comment>/g,$("<div/>").text(b[g][3]).html()).replace(/<image>/g,b[g][4]?"/upload/review/"+b[g][4]:"").replace(/<kind>/g,b[g][5]);$("div#review div.content").append($(review_tr).append(a)).trigger("scroll");$("div#review div.image").click(e.image_preview_e)}});-1!==document.cookie.search(/username=/)&&e.api_post("request=wishlist&op=is_wished&mfcid="+
h,function(a,b){b&&$("div#add2wish").addClass("wished").text($("div#add2wish").data("wished"))},void 0,!1);$("div#review").appendTo("body");$("div#open_review").click(function(){$("div#review").fadeIn()});$("div#close_popup").click(function(){$("div#review").fadeOut().each(function(){$(this).children("div.content")[0].scrollTop=0})});$("div#add2wish").click(function(){-1!==document.cookie.search(/username=/)&&e.api_post("request=wishlist&op=toggle&mfcid="+h,function(a,b){b?$("div#add2wish").addClass("wished").text($("div#add2wish").data("wished")):
$("div#add2wish").removeClass("wished").text($("div#add2wish").data("ori"))})});$("div#open_more_action").click(function(){$("div#more_action").fadeToggle()});$("div#more_action div#user div[id]").click(function(){$("div#open_more_action").click();var a=$("div#cs_page div#cs_info div."+$(this).attr("id"));dialog(void 0,$(this).text(),a.html())});$("div#more_action div#admin div[id]").click(function(){window.open("http://admin.foxe6.kozow.com/shop?"+$(this).text()+"&mfcid="+h,"_blank")});$(window).keyup(function(a){"`"===
a.key&&$("div#more_action div#admin").show()});var v=$("div#review div.content");e.setup_scroll_hints(v);v.trigger("scroll");$("a#toc_toggle").click(function(a){a.stopPropagation();a.preventDefault();a=$(this).data("state")?0:1;$(this).data("state",a);$(this).text($(this).data(a.toString()));$("div#toc").toggle();a=$("div#item")[0].scrollTop;$("div#item")[0].scrollTop=0;$("div#item")[0].scrollTop=a;$("div#item")[0].scrollTop+=7*$("div#menu").height()-$("div#toc_top").outerHeight()})};
