var _location=$("meta[name='description']").attr("content"),order_item='<a class="order_item row" href="/order/<key>">    <div class="top_info">        <div class="timestamp">訂單 <timestamp></div>        <div class="state"><state_text></div>    </div>    <div class="skus"><order_item></div></a>',order_item_img='<div class="image flex pointer<castoff>">    <img src="<src>" />    <div class="quantity no_translate">×<quantity></div></div>',order_info_tracking="<div class='row flex header' style='justify-content: space-around; font-size: calc(4 * var(--vh));'><div>運單</div><div><tracking></div></div>",
order_info_invoice="<div class='row flex header' style='justify-content: space-around; font-size: calc(4 * var(--vh));'><div>發票</div><div><a href='https://www.paypal.com/invoice/p/#<invoice>' target='_blank'>前往paypal查看</a></div></div>";
window.order_js=function(e){function u(c,g){e.api_post("request=order&op=get&state="+c+"&page="+m,function(d,a){d="";if(0===a.length)m=-1,g&&$("div#order_item div#no_order").show(),$("div#order_item .row.last").hide();else{$("div#order_item div#no_order").hide();for(var b=0;b<a.length;b++){for(var f=0;f<a[b].length;f++)if("string"==typeof a[b][f]){for(var h=a[b][f].split("|,|"),l=0;l<h.length;l++)isNaN(h[l])||isNaN(parseFloat(h[l]))||(h[l]=parseInt(h[l]));a[b][f]=h}else a[b][f]=[a[b][f]];h="";for(f=
0;f<a[b][1].length;f++)h+=order_item_img.replace(/<src>/g,e.dialog_resource.img_src_mfcid.replace(/<mfcid>/g,a[b][1][f])).replace(/<quantity>/g,a[b][0][f]).replace(/<castoff>/g,-1===document.cookie.indexOf("off_blur=")&&a[b][2][f]?" blur":"");d+=order_item.replace(/<timestamp>/g,a[b][4]).replace(/<key>/g,btoa(a[b][4])).replace(/<state_text>/g,$("div#order_header select option[value='"+a[b][3][0]+"']").data("text")).replace(/<order_item>/g,h)}$("div#order_item div#order_list .row.last").before(d)}$(window).trigger("resize")});
m++}function n(c){return function(){c&&($("div#order_item div#order_list a.row:not(.last)").remove(),$("div#order_item div#order_list .row.last").show(),m=0);u($("div#order_header select").val(),c)}}delete window.order_js;var p=$.extend({},p,window.common_js());e.setup_dropdown();var q,m=0;$("div#order_item").scroll(function(){clearTimeout(q);0>m||$("div#order_list .row.last").offset().top-$("div#menu").offset().top>9*$("div#menu").height()||(q=setTimeout(n(!1),333))});$("div#order_header select").change(n(!0));
$("div#order_list .row.last").click(n(!1));var k=window.location.pathname.split("/").slice(2,3)[0];if(k){var v=function(){$("div#order_action div#delete").click(function(){confirm(e.dialog_resource.confirm_order_delete,function(c){c&&e.api_post("request=order&op=delete&key="+k,function(g,d){success(e.dialog_resource.success_order_delete,function(a){window.location.href="/order"})})})})},w=function(){$("div#order_action div#checkout").click(function(){window.location.href=window.location.href.replace("/order/",
"/checkout/")})},x=function(){var c=$("div#review_page");c.appendTo("body").find("div#close_popup").click(function(){$(this).closest("div.popup_page").fadeOut()});$("div#review").click(function(){$("div#review_page").fadeIn()});var g={};e.setup_select_img(c,g);$("div#upload_proof div#submit").click(function(d){0===g.selected_file_e[0].files.length?alert(e.dialog_resource.alert_upload_proof_select):10485760<g.selected_file_e[0].files[0].size?(d.target.value="",alert(e.dialog_resource.alert_upload_proof_oversize)):
(d=$("textarea[name='comment']").val(),e.api_post("request=review&op=submit&key="+k+"&comment="+encodeURIComponent(d)+"&file="+g.selected_file[0]+"&ext="+g.selected_file[1],function(a,b){success(e.dialog_resource.success_review,function(f){window.location.href=window.location.href.replace(/checkout/g,"order")});throw"page reloading";}))});$("div#upload_proof_preview").click(e.image_preview_e)},t=function(c){r(c);$("div#order_info").prepend(order_info_tracking.replace(/<tracking>/g,c[1][0][14]))},
r=function(c){$("div#order_info").prepend(order_info_invoice.replace(/<invoice>/g,c[1][0][15]))};k=atob(k);$("div#order_header").hide();$("div#response").remove();$("div#order_item").remove();$("div#order_descriptor span").remove();$("div#order_descriptor div#key").html(k);e.api_post("request=order&op=get&key="+k,function(c,g){var d;p.gen_checkout_order_item(g,"div#order_info",function(a){d=a;return"ｉ"},e);0===d?($("div#order_action div#checkout").show(),w()):2===d?r(g):3===d?($("div#order_action div#review").show(),
t(g),x()):4===d?t(g):-1===d&&($("div#order_action div#delete").show(),v())});$("div#order_action div#go2order").click(function(){window.location.href="/order"})}else $("div#order_action").remove(),$("div#order_info").remove(),$("div#order_descriptor div#key").remove(),$("div#order_descriptor").remove(),$("div#order_header select").trigger("change")};
