var _location=$("meta[name='description']").attr("content"),order_item='<a class="order_item row" href="/order/<key>">    <div class="top_info">        <div class="timestamp">訂單 <timestamp></div>        <div class="state"><state_text></div>    </div>    <div class="skus"><order_item></div></a>',order_item_img='<div class="image flex">    <img<castoff> src="<src>" />    <div class="quantity">×<quantity></div></div>',order_info_tracking="<div class='row flex header' style='justify-content: space-around; font-size: 4vh;'><div>運單</div><div><tracking></div></div>";
window.order_js=function(c){function r(g,f){c.api_post("request=order&op=get&state="+g+"&page="+m,function(d,a){d="";if(0===a.length)m=-1,f?$("div#order_item div#no_order").show():$("div#order_item div.row.last").hide();else{$("div#order_item div#no_order").hide();for(var b=0;b<a.length;b++){for(var e=0;e<a[b].length;e++)if("string"==typeof a[b][e]){for(var h=a[b][e].split("|,|"),l=0;l<h.length;l++)isNaN(h[l])||isNaN(parseFloat(h[l]))||(h[l]=parseInt(h[l]));a[b][e]=h}else a[b][e]=[a[b][e]];h="";for(e=
0;e<a[b][1].length;e++)h+=order_item_img.replace(/<src>/g,c.dialog_resource.img_src_mfcid.replace(/<mfcid>/g,a[b][1][e])).replace(/<quantity>/g,a[b][0][e]).replace(/<castoff>/g,a[b][2][e]&&-1===document.cookie.indexOf("off_blur")?" class='blur'":"");d+=order_item.replace(/<timestamp>/g,a[b][4]).replace(/<key>/g,btoa(a[b][4])).replace(/<state_text>/g,$("div#order_header select option[value='"+a[b][3][0]+"']").data("text")).replace(/<order_item>/g,h)}$("div#order_item div#order_list div.row.last").before(d)}$(window).trigger("resize")});
m++}function n(g){return function(){g&&($("div#order_item div#order_list a.row").remove(),$("div#order_item div#order_list div.row.last").show(),m=0);r($("div#order_header select").val(),g)}}delete window.order_js;var p=$.extend({},p,window.common_js());c.setup_dropdown();var q,m=0;$("div#order_item").scroll(function(){clearTimeout(q);0>m||$("div#order_list div.row.last").offset().top>.9*$(window).height()||(q=setTimeout(n(!1),333))});$("div#order_header select").change(n(!0));$("div#order_list div.row.last").click(n(!1));
var k=window.location.pathname.split("/").slice(2,3)[0];if(k){var t=function(){$("div#order_action div#delete").click(function(){confirm(c.dialog_resource.confirm_order_delete,function(g){g&&c.api_post("request=order&op=delete&key="+k,function(f,d){success(c.dialog_resource.success_order_delete,function(a){window.location.href="/order"})})})})},u=function(){$("div#order_action div#checkout").click(function(){window.location.href=window.location.href.replace("/order/","/checkout/")})},v=function(){var g=
$("div#review_page");g.appendTo("body").find("div#close_popup").click(function(){$(this).closest("div.popup_page").fadeOut()});$("div#review").click(function(){$("div#review_page").fadeIn()});var f={};c.setup_select_img(g,f);$("div#upload_proof div#submit").click(function(d){0===f.selected_file_e[0].files.length?alert(c.dialog_resource.alert_upload_proof_select):10485760<f.selected_file_e[0].files[0].size?(d.target.value="",alert(c.dialog_resource.alert_upload_proof_oversize)):(d=$("textarea[name='comment']").val(),
c.api_post("request=review&op=submit&key="+k+"&comment="+encodeURIComponent(d)+"&file="+f.selected_file[0]+"&ext="+f.selected_file[1],function(a,b){success(c.dialog_resource.success_review,function(e){window.location.href=window.location.href.replace(/checkout/g,"order")});throw"page reloading";}))});$("div#upload_proof_preview").click(c.image_preview_e)};k=atob(k);$("div#order_header").hide();$("div#response").remove();$("div#order_item").remove();$("div#order_descriptor span").remove();$("div#order_descriptor div#key").html(k);
c.api_post("request=order&op=get&key="+k,function(g,f){var d;p.gen_checkout_order_item(f,"div#order_info",function(a){d=a;return"ｉ"},c);0===d?($("div#order_action div#checkout").show(),u()):3===d?($("div#order_action div#review").show(),$("div#order_info").prepend(order_info_tracking.replace(/<tracking>/g,f[0][14])),v()):4===d?$("div#order_info").prepend(order_info_tracking.replace(/<tracking>/g,f[0][14])):-1===d&&($("div#order_action div#delete").show(),t())});$("div#order_action div#go2order").click(function(){window.location.href=
"/order"})}else $("div#order_action").remove(),$("div#order_info").remove(),$("div#order_descriptor div#key").remove(),$("div#order_descriptor").remove(),$("div#order_header select").trigger("change")};
