var _location=$("meta[name='description']").attr("content"),search_result_row='<div class="row">    <div class="image flex pointer<castoff>"><img src="<src>" referrerpolicy="no-referrer" /></div>    <a href="/item/<mfcid>" target="_blank"><name></a></div>',label_input='<label class="pointer<class>"><input type="radio" name="<name>" value="<key>" /> <value></label>';
window.search_js=function(g){function n(a,b,e){$("div#search_result, div#search_result_header").show();$("div#search_filter div[id].rows div.row span.toggle").each(function(){$(this).hasClass("hide")||$(this).parent().click()});$("div#search_result div.row.first").show();g.api_post("request=search&keyword="+encodeURIComponent(a[0])+a[1]+"&page="+h,function(c,d){if(0===d.length)h=-1,b?$("div#search_result div#no_result").show():$("div#search_result div.row.last").hide();else{for(c=0;c<d.length;c++){var f=
d[c][1];a[0]&&(f=f.replace(new RegExp("("+a[0].replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")+")","gi"),"<span style='background-color: var(--foxe6a);'>$1</span>"));$("div#search_result div.row.last").before(search_result_row.replace(/<src>/g,d[c][3]||g.dialog_resource.img_src_mfcid.replace(/<mfcid>/g,d[c][0])).replace(/<castoff>/g,d[c][2]?" blur":"").replace(/<mfcid>/g,d[c][0]).replace(/<name>/g,f))}-1!==document.cookie.indexOf("off_blur=")?$("div#search_result div.row:not(.last)").off("click").click(g.image_preview_e):
$("div#search_result div.row:not(.last) > div:not(.blur)").parent().off("click").click(g.image_preview_e)}$(window).trigger("resize");e&&e()});h++}function l(a,b){return function(){var e=$("div#search_box form.simple div.input input").val(),c=$("div#search_filter form").serialize();c=c?"&"+c:"";if(a||!e&&!c)$("div#search_result div.row:not(.last)").remove(),$("div#search_result div.row.last").show();a&&(h=0);if(e||c){for(var d=Array.from(c.matchAll(/([a-z]+)=/g),function(p){return p}),f=[],k=0;k<
d.length;k++)-1===f.indexOf(d[k][1])&&(f.push(d[k][1]),c+="&meta="+d[k][1]);n([e,c],a,b)}}}delete window.search_js;g.api_post("request=metadata",function(a,b){for(a=0;a<b.length;a++)if(!(0>b[a][1])){var e=["classification","company"].indexOf(b[a][0]),c=$("div#search_filter div#"+b[a][0]+" fieldset");c.attr("id",b[a][0]);c.append(label_input.replace(/<name>/g,b[a][0]).replace(/<meta>/g,b[a][0]).replace(/<key>/g,b[a][1]).replace(/<value>/g,b[a][2]).replace(/<class>/g,-1===e?"":" no_translate"))}$("div#search_filter div.table div.td#company").prev().click();
$("div#search_filter div.table div.td#classification").prev().click();$("div#search_filter div#sorting div.row").click();window.location.search&&(a=window.location.search.match(/^\?([a-z]+)=(.*?)$/),b=a[1],a=a[2],"keyword"===b?$("input[name='"+b+"']").val(decodeURIComponent(a)):$("input[name='"+b+"'][value='"+a+"']").prop("checked",!0),$("div#menu div#search_icon").click())});$("div#search_filter div.table div.td span.toggle").parent().click(function(){var a=$(this).find("span.toggle");$(a).toggleClass("hide");
$(a).hasClass("hide")?$(a).parent().next().children().hide().filter("div.toggle_hide_hint").show():$(a).parent().next().children().show().filter("div.toggle_hide_hint").hide();$(window).trigger("resize")});$("div#search_filter div[id].rows .row span.toggle").parent().click(function(){var a=$(this).find("span.toggle");$(a).toggleClass("hide");$(a).hasClass("hide")?$(this).closest("div.rows").next().hide():$(this).closest("div.rows").next().show();$(window).trigger("resize")});$("input#filter_classification, input#filter_company").keyup(function(){var a=
$(this).val().toLowerCase(),b=$(this).parent().parent().children("label");b.show();a&&b.each(function(){-1===$(this).text().trim().toLowerCase().indexOf(a)&&$(this).hide()})});var m,h=0;$("div#menu div#search_icon").off("click").click(function(){$("div#search_submit").click()});$("div#search_submit").click(l(!0,function(){$("div#search")[0].scrollTop=$("div#search_result_header").offset().top-2*$("div#menu").height()}));$("div#search_box form.simple div.input input").keydown(function(a){13===a.keyCode&&
(a.stopPropagation(),a.preventDefault(),$(this).blur(),l(!0,function(){$("div#search")[0].scrollTop=$("div#search_result_header").offset().top-2*$("div#menu").height()})())});$("div#search").scroll(function(){clearTimeout(m);0>h||"none"!==getComputedStyle($("div#search_result")[0]).display&&($("div#search_result div.row.last").offset().top-$("div#menu").offset().top>9*$("div#menu").height()||(m=setTimeout(l(!1),333)))});$("div#search_result div.row.last").click(l(!1));$(window).resize(function(){$("div#search_result.rows .row div.image").each(function(){$(this).css({height:$(this).width()+
"px"})})});$("div#search_reset").click(function(){window.location.href="/search"})};
