window.cart_js=function(f){delete window.cart_js;var e,t=!0,n,l,g,C,u={};$.get("/common.html",function(a){$(a).filter("div#stock").appendTo("body");$("div#for_cart").hide();$("div#stock div.bg").click(function(){$("div#stock").fadeOut();$("div#stock > div.content").effect("slide",{mode:"hide",direction:"down"})});$("div#quantity_plus").click(function(){if(n&&t&&!(9<l+1)){for(var c,b=0;b<e.length;b++)if(e[b].sku===n){c=e[b].quantity-e[b].ordered;break}l+1>c||(t=!1,l++,$("div#quantity div.selected").removeClass("selected").next().addClass("selected"),
$("div#quantity_wrapper div#unit").animate({top:"-="+$("div#quantity_wrapper div#unit").height()/9+"px"},function(){t=!0}))}});$("div#quantity_minus").click(function(){!n||!t||0>=l-1||(t=!1,l--,$("div#quantity div.selected").removeClass("selected").prev().addClass("selected"),$("div#quantity_wrapper div#unit").animate({top:"+="+$("div#quantity_wrapper div#unit").height()/9+"px"},function(){t=!0}))});$("div#stock div#add_to_cart_descriptor").click(function(){if(!n||0===l)return alert(f.dialog_resource.alert_sku_select);
var c=n,b=C,k=u[b],w=l;if(c===b&&w===k)$("div#stock div.bg").click();else{for(var x=0;x<e.length;x++)if(e[x].sku===c&&c!==b)return alert(f.dialog_resource.alert_cart_exist);u="&old_sku="+b;u=u.repeat(k);b=("&new_sku="+c).repeat(w);f.api_post("request=cart&op=update"+u+b,function(A,y){window.location.href="/cart#"+c;window.location.reload(!0)})}})});f.api_post("request=cart&op=get",function(a,c){if(0!==c.length){g=c;$("div#cart_info").html("");for(a=0;a<g.length;a++){c=g[a].sku;var b=g[a].mfcid,k=
g[a].name,w=g[a].castoff,x=g[a].kind,A=g[a]["final"],y=g[a].quantity;k=cart_item.replace(/<src>/g,f.dialog_resource.img_src_mfcid.replace(/<mfcid>/g,b)).replace(/<castoff>/g,w&&-1===document.cookie.indexOf("off_blur")?" class='blur'":"").replace(/<quantity>/g,y).replace(/<mfcid>/g,b).replace(/<name>/g,k).replace(/<kind>/g,x).replace(/<price>/g,A).replace(/<total>/g,y*A);k=$(k);k.find("div.edit").click(function(B,m,v){return function(){C=m;u[m]=v;f.api_post("request=item_sku&mfcid="+B,function(p,q){e=
q;$("div#stock div#skus select").html("");for(p=0;p<e.length;p++){q=e[p].kind;q=$("<option/>").attr("value",q).text(q);var z=e[p].late_po||e[p].deadline;0===e[p].status[0][0]&&z&&(z=str2epoch(z),z<=epoch()&&q.addClass("disabled"));e[p].quantity===e[p].ordered&&q.addClass("disabled");$("div#stock div#skus select").append(q)}f.setup_dropdown();$("div#stock div#skus select").off("change").change(function(){console.log([$(this).val(),e[d].kind]);for(var d=0;d<e.length;d++)if($(this).val()===e[d].kind){var h=
e[d];break}n=h.sku;l=n===m?v:1;d=h.late_po||h.deadline;0===h.status[0][0]&&d&&(d=str2epoch(d),d<=epoch()&&(n=null,alert(f.dialog_resource.alert_sku_deadline.replace(/<kind>/g,h.kind))));d=h.quantity-h.ordered;l>d&&(l=d,alert(f.dialog_resource.alert_sku_max_quantity.replace(/<kind>/g,h.kind).replace(/<max_quantity>/g,d)));h.quantity===h.ordered&&(n=null,alert(f.dialog_resource.alert_sku_stock.replace(/<kind>/g,h.kind)));for(d=0;d<Object.keys(h).length;d++){var r=Object.keys(h)[d];if("image"!==r){var D=
$("div#stock div#sku_info div#"+r+" span");0!==D.length&&(r=h[r],null!==r&&""!==r&&D.html(r))}}$("div#stock div#quantity div#unit").animate({top:"-"+$("div#stock div#quantity div#unit").height()/9*(l-1)+"px"})});$("div#stock").fadeIn();$("div#stock > div.content").hide().effect("slide",{mode:"show",direction:"down"},function(){$("div#stock div#skus select").val($("div#stock div#skus select option").eq(e.findIndex(function(d){return d.sku===m})).data("text")).trigger("change")})})}}(b,c,y));k.find("div.image").click(f.image_preview_e);
k.find("div.checkbox").click(function(){$(this).children().hasClass("active")?$(this).children().removeClass("active"):$(this).children().addClass("active");var B=$("div.checkbox div.dot.active").map(function(m,v){m=$("div.item div.checkbox div.dot").index(v);return g[m]["final"]*g[m].quantity}).get().reduce(function(m,v){return m+v},0);$("div#place_order div#subtotal span").text(B)});$("div#cart_info").append(k)}$(window).trigger("resize");a=window.location.hash.slice(1);0<a.length&&(window.location.hash=
"",a=$("div[data-sku='"+a+"']"),1===a.length&&$("div#cart_info").animate({scrollTop:a.offset().top-20.6*$(window).height()/100}))}},void 0,!1);$("div#select_all").click(function(){$("div.dot").length===$("div.dot.active").length?$("div.dot").click():$("div.dot:not(.active)").click()});$("div#delete_selected").click(function(){if(0===$("div.item div.checkbox div.dot.active").length)return alert(f.dialog_resource.alert_item_select);confirm(f.dialog_resource.confirm_cart_delete,function(a){if(a){var c=
"";$("div.item div.checkbox div.dot").each(function(){if($(this).hasClass("active")){var b=$("div.item div.checkbox div.dot").index(this);c+=("&sku="+g[b].sku).repeat(g[b].quantity)}});f.api_post("request=cart&op=delete"+c,function(b,k){success(f.dialog_resource.success_cart_delete,function(w){window.location.reload(!0)})})}})});$("div#checkout").click(function(){if(0===$("div.item div.checkbox div.dot.active").length)return alert(f.dialog_resource.alert_item_select);var a="";$("div.item div.checkbox div.dot").each(function(){if($(this).hasClass("active")){var c=
$("div.item div.checkbox div.dot").index(this);a+=("&sku="+g[c].sku).repeat(g[c].quantity)}});f.api_post("request=checkout&op=reserve_order"+a,function(c,b){window.location.href="/checkout/"+btoa(b.key)})});$(window).resize(function(){$("div#cart_info div.item div.name").each(function(){$(this).next().removeAttr("style").parent().removeClass("valign");10<$(this).height()+$(this).next().height()-$(this).parent().prev().outerHeight(!0)?$(this).next().css({clear:"both",marginLeft:"1vh"}):$(this).parent().addClass("valign")})})};
