window.item_js=function(f){delete window.item_js;var m=window.location.href.split("/item/").slice(-1)[0],b,t=!0,n,l;$.get("/common.html",function(c){$(c).filter("div#stock").appendTo("body");$("div#for_item").hide();$("div#stock div.bg").click(function(){$("div#stock").fadeOut();$("div#stock > div.content").effect("slide",{mode:"hide",direction:"down"})});$("div#quantity_plus").click(function(){if(n&&t&&!(9<l+1)){for(var a,d=0;d<b.length;d++)if(b[d][0]===n){a=b[d][5]-b[d][10];break}l+1>a||(t=!1,l++,
$("div#quantity div.selected").removeClass("selected").next().addClass("selected"),$("div#quantity_wrapper div#unit").animate({top:"-="+$("div#quantity_wrapper div#unit").height()/9+"px"},function(){t=!0}))}});$("div#quantity_minus").click(function(){!n||!t||0>=l-1||(t=!1,l--,$("div#quantity div.selected").removeClass("selected").prev().addClass("selected"),$("div#quantity_wrapper div#unit").animate({top:"+="+$("div#quantity_wrapper div#unit").height()/9+"px"},function(){t=!0}))});$("div#add_to_cart_descriptor").click(function(){if(!n||
0===l)return alert(f.dialog_resource.alert_sku_select);var a="&sku="+n;a=a.repeat(l);f.api_post("request=cart&op=add"+a,function(d,p){success(f.dialog_resource.success_sku_select)})});$("div#select_sku").click(function(){f.api_post("request=item_sku&mfcid="+m,function(a,d){b=d;console.log(b);$("div#stock div#skus select").html("");for(a=0;a<b.length;a++){d=b[a][3];d=$("<option/>").data("text",d).text(d);var p=b[a][9]||b[a][7];0===b[a][11][0][0]&&p&&(p=str2epoch(p),p<=epoch()&&d.addClass("disabled"));
b[a][5]===b[a][10]&&d.addClass("disabled");$("div#stock div#skus select").append(d)}f.setup_dropdown();$("div#stock div#skus select").unbind("change").change(function(){for(var e=0;e<b.length&&$(this).val()!==b[e][3];e++);n=b[e][0];l=1;var h=b[e][9]||b[e][7];0===b[e][11][0][0]&&h&&(h=str2epoch(h),h<=epoch()&&(n=null,alert(f.dialog_resource.alert_sku_deadline.replace(/<kind>/g,b[e][3]))));b[e][5]===b[e][10]&&(n=null,alert(f.dialog_resource.alert_sku_stock.replace(/<kind>/g,b[e][3])));for(h=0;h<b[e].length;h++){var k=
$("div#stock div#sku_info div[j='"+h+"'] span");if(0!==k.length){var q=b[e][h];null!==q&&""!==q&&k.text(q)}}$("div#stock div#quantity div#unit").animate({top:"-"+$("div#stock div#quantity div#unit").height()/9*(l-1)+"px"})});$("div#stock").fadeIn();$("div#stock > div.content").hide().effect("slide",{mode:"show",direction:"down"},function(){$("div#stock div#skus select").trigger("change")})})});f.api_post("request=views&mfcid="+m,void 0,void 0,!1)});f.api_post("request=item_info&mfcid="+m,function(c,
a){function d(g){$("div#loading").fadeIn();f.image_preview_e(g,!1);var r=setInterval(function(){$("div#preview img")[0].complete&&(clearInterval(r),$("div#loading").fadeOut())},100),y=!!g.target;g=g.target||g;u=v.index(g);$("div#preview div.description").html(u+1+" / "+v.length);y?$("div#preview").fadeIn():$("div#preview").show();$("div#preview div.preview_next, div#preview div.preview_prev").css({display:"flex"})}function p(g){return function(r){r.preventDefault();r.stopPropagation();0<g&&u+1<=v.length-
1?d(v[u+1]):0>g&&0<=u-1&&d(v[u-1])}}function e(){w[0].scrollTo(0,0);setTimeout(function(){var g=w.children().outerWidth(),r=w.width();g>r?w.animate({scrollLeft:g-r},9*g,"linear",function(){setTimeout(e,1E3)}):setTimeout(e,1E3)},1E3)}console.log(a);for(c=0;c<a.length;c++)if(6!==c){var h=$("div#item div#item_info div[i='"+c+"'] span");if(0!==h.length){var k=a[c];if(Array.isArray(k)){for(var q="",x=0;x<k.length;x++)q&&(q+="・"),q+=item_info_a.replace(/<text>/g,k[x][1]).replace(/<k>/g,h.parent().attr("id")).replace(/<v>/g,
k[x][0]);k=q}null!==k&&h.html(k)}}c=f.dialog_resource.img_src_mfcid.replace(/<mfcid>/g,m);0<a[6].length?a[6].unshift(c):a[6]=[c];(new Slideshow).setup(a[6],d);var v=$("div.glider-track div.glider-slide"),u=0;$("div#preview div.preview_next").click(p(1));$("div#preview div.preview_prev").click(p(-1));1===a[4]&&-1===document.cookie.indexOf("off_blur")&&($("#slideshow img").addClass("blur"),warn("<div>本網頁可能含有令人反感、十六歲以上、成人內容。\n未滿十六歲人士必須在成人陪同下瀏覽本網頁。\n本網域嚴禁虛報年齡或違法進入等行為。</div>",{cancel:"離開",confirm:"同意並進入"},
function(g){g?$("#slideshow img").removeClass("blur"):($("#slideshow img").parent().off("mousedown"),window.history.back())}));var w=$("div#item_info div#name");w.click(function(){dialog(void 0,"商品名稱",$(this).text().replace(/・/g,"<br/>"))});e()});f.api_post("request=review&op=get&mfcid="+m,function(c,a){if(0!==a.length){$("div#review #no_review").hide();$("div#review span#amount_review").text(a.length);for(c=0;c<a.length;c++)$("div#review div.table div.tbody").append(review_tr.replace(/<timestamp>/g,
a[c][0]).replace(/<buyer>/g,a[c][1]).replace(/<comment>/g,$("<div/>").text(a[c][3]).html()).replace(/<image>/g,a[c][4]||""));$("div#review div.image").click(f.image_preview_e)}});f.api_post("request=wishlist&op=is_wished&mfcid="+m,function(c,a){a&&$("div#add2wish").addClass("wished").text($("div#add2wish").data("wished"))},void 0,!1);$("div#review").appendTo("body");$("div#open_review").click(function(){$("div#review").fadeIn()});$("div#close_popup").click(function(){$("div#review").fadeOut().each(function(){$(this).children("div.content")[0].scrollTop=
0})});$("div#add2wish").click(function(){f.api_post("request=wishlist&op=toggle&mfcid="+m,function(c,a){a?$("div#add2wish").addClass("wished").text($("div#add2wish").data("wished")):$("div#add2wish").removeClass("wished").text($("div#add2wish").data("ori"))})});$("div#open_more_action").click(function(){$("div#more_action").fadeToggle()});$("div#more_action div#user div[id]").click(function(){$("div#open_more_action").click();var c=$("div#cs_page div#cs_info div."+$(this).attr("id"));dialog(void 0,
$(this).text(),c.html())});$("div#more_action div#admin div[id]").click(function(){window.open("http://admin.foxe6.kozow.com/shop?"+$(this).text()+"&mfcid="+m,"_blank")});$(window).keyup(function(c){"`"===c.key&&$("div#more_action div#admin").show()})};
