window.item_js=function(d){delete window.item_js;var f=window.location.href.split("/item/").slice(-1)[0],g={item_sku:null,quantity_changed:!0,sku_active:null,quantity_active:null,app:d};$.get("/common.html",function(a){a=d.db64(a);$(a).filter("script").appendTo("head");append_stock(a,"div#for_item");$("div#quantity_plus").click(quantity_plus_e(g));$("div#quantity_minus").click(quantity_minus_e(g));$("div#add_to_cart_descriptor").click(function(){if(!g.sku_active||0===g.quantity_active)return alert(d.dialog_resource.alert_sku_select);
var b="&sku="+g.sku_active;b=b.repeat(g.quantity_active);d.api_post("request=cart&op=add"+b,function(p,r){success(d.dialog_resource.success_sku_select)})});$("div#select_sku").click(function(){setup_sku_select(g,f,function(){return 1},void 0,function(){$("div#stock div#skus select").trigger("change")})});d.api_post("request=views&mfcid="+f,void 0,void 0,!1)});d.api_post("request=item_info&mfcid="+f,function(a,b){function p(c){$("div#loading").fadeIn();d.image_preview_e(c,!1);var h=setInterval(function(){$("div#preview img")[0].complete&&
(clearInterval(h),$("div#loading").fadeOut())},100),v=!!c.target;c=c.target||c;l=m.index(c);$("div#preview div.description").html(l+1+" / "+m.length);v?$("div#preview").fadeIn():$("div#preview").show();$("div#preview div.preview_next, div#preview div.preview_prev").css({display:"flex"})}function r(c){return function(h){h.preventDefault();h.stopPropagation();0<c&&l+1<=m.length-1?p(m[l+1]):0>c&&0<=l-1&&p(m[l-1])}}function t(){n[0].scrollTo(0,0);setTimeout(function(){var c=n.children().outerWidth(),
h=n.width();c>h?n.animate({scrollLeft:c-h},9*c,"linear",function(){setTimeout(t,1E3)}):setTimeout(t,1E3)},1E3)}console.log(b);for(a=0;a<b.length;a++)if(6===a)for(var e=0;e<b[6].length;e++)0===b[6][e].indexOf("|mfc|")&&(b[6][e]=b[6][e].replace("|mfc|","https://static.myfigurecollection.net/upload/pictures/"));else{var u=$("div#item div#item_info div[i='"+a+"'] span");if(0!==u.length){var k=b[a];if(Array.isArray(k)){var q="";for(e=0;e<k.length;e++)q&&(q+="・"),q+=item_info_a.replace(/<text>/g,k[e][1]).replace(/<k>/g,
u.parent().attr("id")).replace(/<v>/g,k[e][0]);k=q}null!==k&&u.html(k)}}a=d.dialog_resource.img_src_mfcid.replace(/<mfcid>/g,f);0<b[6].length?b[6].unshift(a):b[6]=[a];(new Slideshow).setup(b[6],p);var m=$("div.glider-track div.glider-slide"),l=0;$("div#preview div.preview_next").click(r(1));$("div#preview div.preview_prev").click(r(-1));1===b[4]&&-1===document.cookie.indexOf("off_blur")&&($("#slideshow img").addClass("blur"),warn("<div>本網頁可能含有令人反感、十六歲以上、成人內容。\n未滿十六歲人士必須在成人陪同下瀏覽本網頁。\n本網域嚴禁虛報年齡或違法進入等行為。</div>",
{cancel:"離開",confirm:"同意並進入"},function(c){c?$("#slideshow img").removeClass("blur"):($("#slideshow img").parent().off("mousedown"),window.history.back())}));var n=$("div#item_info div#name");n.click(function(){dialog(void 0,"商品名稱",$(this).text().replace(/・/g,"<br/>"))});t()});d.api_post("request=review&op=get&mfcid="+f,function(a,b){if(0!==b.length){$("div#review #no_review").hide();$("div#review span#amount_review").text(b.length);for(a=0;a<b.length;a++)$("div#review div.table div.tbody").append(review_tr.replace(/<timestamp>/g,
b[a][0]).replace(/<buyer>/g,b[a][1]).replace(/<comment>/g,$("<div/>").text(b[a][3]).html()).replace(/<image>/g,b[a][4]?"/upload/review/"+b[a][4]:""));$("div#review div.image").click(d.image_preview_e)}});d.api_post("request=wishlist&op=is_wished&mfcid="+f,function(a,b){b&&$("div#add2wish").addClass("wished").text($("div#add2wish").data("wished"))},void 0,!1);$("div#review").appendTo("body");$("div#open_review").click(function(){$("div#review").fadeIn()});$("div#close_popup").click(function(){$("div#review").fadeOut().each(function(){$(this).children("div.content")[0].scrollTop=
0})});$("div#add2wish").click(function(){d.api_post("request=wishlist&op=toggle&mfcid="+f,function(a,b){b?$("div#add2wish").addClass("wished").text($("div#add2wish").data("wished")):$("div#add2wish").removeClass("wished").text($("div#add2wish").data("ori"))})});$("div#open_more_action").click(function(){$("div#more_action").fadeToggle()});$("div#more_action div#user div[id]").click(function(){$("div#open_more_action").click();var a=$("div#cs_page div#cs_info div."+$(this).attr("id"));dialog(void 0,
$(this).text(),a.html())});$("div#more_action div#admin div[id]").click(function(){window.open("http://admin.foxe6.kozow.com/shop?"+$(this).text()+"&mfcid="+f,"_blank")});$(window).keyup(function(a){"`"===a.key&&$("div#more_action div#admin").show()})};
