window.order_js=function(e){function q(f,h){e.api_post("request=order&op=get&state="+f+"&page="+m,function(c,a){c="";if(0===a.length)m=-1,h?$("div#order_item div#no_order").show():$("div#order_item div.row.last").hide();else{$("div#order_item div#no_order").hide();for(var b=0;b<a.length;b++){for(var d=0;d<a[b].length;d++)if("string"==typeof a[b][d]){for(var g=a[b][d].split("|,|"),l=0;l<g.length;l++)isNaN(g[l])||isNaN(parseFloat(g[l]))||(g[l]=parseInt(g[l]));a[b][d]=g}else a[b][d]=[a[b][d]];g="";for(d=
0;d<a[b][1].length;d++)g+=order_item_img.replace(/<src>/g,e.dialog_resource.img_src_mfcid.replace(/<mfcid>/g,a[b][1][d])).replace(/<quantity>/g,a[b][0][d]).replace(/<castoff>/g,a[b][2][d]&&-1===document.cookie.indexOf("off_blur")?" class='blur'":"");c+=order_item.replace(/<timestamp>/g,a[b][4]).replace(/<key>/g,btoa(a[b][4])).replace(/<state_text>/g,$("div#order_header select option[value='"+a[b][3][0]+"']").data("text")).replace(/<order_item>/g,g)}$("div#order_item div#order_list div.row.last").before(c)}$(window).trigger("resize")});
m++}function n(f){return function(){f&&($("div#order_item div#order_list a.row").remove(),$("div#order_item div#order_list div.row.last").show(),m=0);q($("div#order_header select").val(),f)}}delete window.order_js;e.setup_dropdown();var p,m=0;$("div#order_item").scroll(function(){$(window).trigger("resize");clearTimeout(p);0>m||$("div#order_list div.row.last").offset().top>.9*$(window).height()||(p=setTimeout(n(!1),333))});$("div#order_header select").change(n(!0));$("div#order_list div.row.last").click(n(!1));
var k=window.location.pathname.split("/").slice(2,3)[0];if(k){var r=function(){$("div#order_action div#delete").click(function(){confirm(e.dialog_resource.confirm_order_delete,function(f){f&&e.api_post("request=order&op=delete&key="+k,function(h,c){success(e.dialog_resource.success_order_delete,function(a){window.location.href="/order"})})})})},t=function(){$("div#order_action div#checkout").click(function(){window.location.href=window.location.href.replace("/order/","/checkout/")})},u=function(){$("div#review_page").appendTo("body").find("div#close_popup").click(function(){$(this).closest("div.popup_page").fadeOut()});
$("div#review").click(function(){$("div#review_page").fadeIn()});var f,h=$("div#upload_proof form input[type='file']").change(function(c){var a=$("div#upload_proof form label");a.hasClass("active")&&a.removeClass("active").text(a.text().slice(1));$("div#upload_proof_preview img").attr("src","");var b=c.target.files[0];"type"in b&&"image"===b.type.split("/")[0]?10485760<b.size?(c.target.value="",alert(_this.dialog_resource.alert_upload_proof_oversize)):(c=new FileReader,c.onload=function(d){f=d.target.result;
$("div#upload_proof_preview img").attr("src",f);f=[f.split(",").slice(1)[0],b.name.split(".").slice(-1)[0]];a.addClass("active").text(e.dialog_resource.text_upload_proof_1)},c.readAsDataURL(b)):(c.target.value="",alert(_this.dialog_resource.alert_upload_proof_type))});$("div#upload_proof div#submit").click(function(c){0===h[0].files.length?alert(e.dialog_resource.alert_upload_proof_select):10485760<h[0].files[0].size?(c.target.value="",alert(e.dialog_resource.alert_upload_proof_oversize)):(c=$("textarea[name='comment']").val(),
e.api_post("request=review&op=submit&key="+k+"&comment="+encodeURIComponent(c)+"&file="+f[0]+"&ext="+f[1],function(a,b){success(e.dialog_resource.success_review,function(d){window.location.href=window.location.href.replace(/checkout/g,"order")});throw"page reloading";}))});$("div#upload_proof_preview").click(e.image_preview_e)};k=atob(k);$("div#order_header").hide();$("div#response").remove();$("div#order_item").remove();$("div#order_descriptor span").remove();$("div#order_descriptor div#key").html(k);
e.api_post("request=order&op=get&key="+k,function(f,h){$.get("/common.html",function(c){var a;$("body").append(c);gen_checkout_order_item(h,"div#order_info",function(b){a=b;return"ｉ"},e);0===a?($("div#order_action div#checkout").show(),t()):3===a?($("div#order_action div#review").show(),$("div#order_info").prepend(order_info_tracking.replace(/<tracking>/g,h[0][7])),u()):-1===a&&($("div#order_action div#delete").show(),r())})});$("div#order_action div#go2order").click(function(){window.location.href=
"/order"})}else $("div#order_action").remove(),$("div#order_info").remove(),$("div#order_descriptor div#key").remove(),$("div#order_descriptor").remove(),$("div#order_header select").trigger("change")};
