(function(a){function r(){var h=function(){var d=[],f=$("div#slideshow div.glider");$("body *").each(function(){for(var b=0;b<f.length;b++)if(f[b]===this)return;b=getComputedStyle(this);"auto"!==b.overflow&&"auto"!==b.overflowX&&"auto"!==b.overflowY||d.push(this)});return d},k=[],l=function(){},m=function(){};$(window).resize(function(){k.map(function(d){d.resize()})});var t=function(){k=[];for(var d=h(),f=0;f<d.length;f++){var b={cursorcolor:"var(--foxe6)",cursoropacitymin:.33,cursoropacitymax:.75,
cursorwidth:"1vh",cursorborder:"none",cursorborderradius:"0.5vh",grabcursorenabled:!1};"hidden"===getComputedStyle(d[f]).overflowX&&(b.horizrailenabled=!1);b=$(d[f]).niceScroll(b);k.push(b)}$(window).trigger("resize");$("div#nav div#go2top").click(function(){k.map(function(e){e.doScrollTop(0,333)})});l=function(){var e=$(this).getNiceScroll();0!==e.length&&(e.resize(),e[0].doScrollTop(1,1),e[0].doScrollLeft(1,1),setTimeout(function(){e[0].doScrollTop(0,0);e[0].doScrollLeft(0,0)},100))};m=function(){$(this).find("*").each(l)}},
u=function(){$("div#nav div#go2top").off("click").click(function(){h().map(function(d){d.scrollTo(d.scrollLeft,0)})})},c=!1;"maxTouchPoints"in navigator?c=0<navigator.maxTouchPoints:"msMaxTouchPoints"in navigator?c=0<navigator.msMaxTouchPoints:(c=window.matchMedia&&matchMedia("(pointer:coarse)"))&&"(pointer:coarse)"===c.media?c=!!c.matches:"orientation"in window?c=!0:(c=navigator.userAgent,c=/\b(BlackBerry|webOS|iPhone|IEMobile)\b/i.test(c)||/\b(Android|Windows Phone|iPad|iPod)\b/i.test(c));if(c)var p=
u;else $("body").addClass("desktop"),p=t;var q;$(document).ajaxStop(function(){clearTimeout(q);q=setTimeout(function(){$(document).off("ajaxStop");p();$(".popup_page").bind("fadeIn_callback",m);$(".flyin_dialog > div.content").bind("effect_callback",m);$("table.tabs > thead > tr > td").click(function(){l.apply($(this).closest("table.tabs").parent())})},500)})}(function(){window.addEventListener("pageshow",function(h){if(h.persisted||"undefined"!=typeof window.performance&&2===window.performance.navigation.type)throw window.location.reload(!0),
Error("page reloading");});$("div#loading").hide();a.donation_table("","",!1,"",a.dialog_resource.thx4donation).appendTo("div#donation_page div.content");a.cs_info().appendTo("div#cs_page div.content");$("div#right_menu div#logout, div#right_menu div#cs, div#right_menu div.logged_in").hide();a.check_agreed_tos();-1!==document.cookie.indexOf("username=")?(a.check_ban(),$("div#right_menu div#login, div#right_menu div#register").hide(),$("div#right_menu div#logout, div#right_menu div#cs, div#right_menu div.logged_in").show(),
a.check_understood_rarp_shipping()):(a.login_form().appendTo("div#login_page div.content"),a.register_form().appendTo("div#register_page div.content"),a.login_register_form_e())})();(function(){$("div#preview").click(function(){$(this).fadeOut(function(){$(this).find("img").attr("src","");$(this).find("div.description").html("")})});$("div#menu div#hamburger").click(function(){$("div#right_menu").fadeIn();$("div#right_menu > div").hide().effect("slide",{mode:"show",direction:"left"})});$("div#right_menu div#close, div#right_menu div#login, div#right_menu div#register, div#right_menu div#cs, div#right_menu div#donation").click(function(){$("div#right_menu").fadeOut();
$("div#right_menu > div").effect("slide",{mode:"hide",direction:"left"})});$("div#menu div#search_icon, div#right_menu div#account, div#right_menu div#wishlist, div#right_menu div#order, div#nav div#news, div#nav div#home, div#nav div#cart, div#right_menu div#faq, div#right_menu div#legal").click(function(){window.location.href=$(this).data("url");throw"page redirecting";});$("div#right_menu div#login, div#right_menu div#register, div#right_menu div#donation, div#right_menu div#cs").click(function(){$("div#"+
$(this).attr("id")+"_page").fadeIn()});$("div#right_menu div#logout").click(a.logout_e);$("div#right_menu div#logout, div#right_menu div#account, div#right_menu div#wishlist, div#right_menu div#order, div#nav div#news, div#nav div#home, div#nav div#cart").click(function(){$("div#loading").fadeIn()});$("div#close_popup").click(function(){$("div#login_page, div#register_page, div#donation_page, div#cs_page").fadeOut().each(function(){$(this).children("div.content")[0].scrollTop=0})})})();setTimeout(function(){window.scrollTo(0,
.05*$("body").height())},100);var n=0;setInterval(function(){$("div#loading img").css({transform:"rotate("+n+"deg)"});n=(n+30)%360},111);var g=window.location.pathname.split("/").slice(1,2)[0];g||(g="index");var v=setInterval(function(){"nav_js"in window&&(clearInterval(v),window.nav_js(a))},100);g+="_js";var w=setInterval(function(){g in window&&(clearInterval(w),window[g](a),r())},100)})(new foxe6);
